/**
 * ClawSec 2.0 — OpenClaw Plugin
 *
 * Registers as an OpenClaw lifecycle-hook plugin.
 * Hooks used:
 *   - subagent_spawning  → inject sub-agent security skills
 *   - before_tool_call   → enforce remediation tier constraints
 *   - session_start      → register coordinator skill routing
 *
 * Install: copy to ~/.openclaw/extensions/clawsec/
 * Manifest: openclaw.plugin.json alongside this file
 */

// CommonJS imports — required for OpenClaw extension loader compatibility
// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require("fs") as typeof import("fs");
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require("path") as typeof import("path");

import type { AgentFinding, ScanReport, SubAgentResult, Severity } from "./coordinator-types";
import { computeRiskScore, scoreLabel, severityRank, shouldAlert } from "./coordinator-risk";
import { loadLastReport, saveReport, appendChangelog } from "./coordinator-reports";
import { executeAutoRemediation } from "./coordinator-remediation";
import { CHECK_ID_PATTERN, IMMUTABLE_FILES, MUTATING_TOOL_NAMES, SCAN_SCHEMA_VERSION } from "./policy";

// ─── Constants ───────────────────────────────────────────────────────────────

const CLAWSEC_ROOT = path.resolve(
  process.env.CLAWSEC_ROOT ||
  path.join(process.env.HOME || "~", ".openclaw/workspace/clawsec")
);

// ── Inter-Agent Auth Token (ASI07) ────────────────────────────────────────────
// Token is generated by server.py on first start and stored at 600 permissions.
// Must be included in X-ClawSec-Token header for all mutating API calls.
const TOKEN_FILE = path.join(CLAWSEC_ROOT, ".clawsec_token");
const CLAWSEC_TOKEN: string = fs.existsSync(TOKEN_FILE)
  ? fs.readFileSync(TOKEN_FILE, "utf-8").trim()
  : "";
const CHECK_ID_REGEX = new RegExp(CHECK_ID_PATTERN);

// Sub-agent skill names — matched to OpenClaw skill registry
const SUB_AGENTS = [
  "clawsec-env",
  "clawsec-perm",
  "clawsec-net",
  "clawsec-session",
  "clawsec-config",
] as const;


// ─── Main Coordinator Logic ───────────────────────────────────────────────────

async function runSecurityScan(
  options: {
    isHeartbeat?: boolean;
    skipAutoFix?: boolean;
  } = {}
): Promise<ScanReport> {
  const { isHeartbeat = false, skipAutoFix = false } = options;
  const startTime = Date.now();
  const previous = loadLastReport();

  console.log(`[CLAWSEC] Starting ${isHeartbeat ? "heartbeat" : "full"} scan`);

  // ── Phase 1: Parallel sub-agent dispatch ─────────────────────────────────
  // In OpenClaw, each sub-agent is invoked via the skill system.
  // Here we simulate via the HTTP backend; in production this maps to
  // OpenClaw's subagent_spawning API.
  const agentResults: Record<string, SubAgentResult> = {};

  await Promise.allSettled(
    SUB_AGENTS.map(async (agentName) => {
      const agentStart = Date.now();
      try {
        const res = await fetch(
          `http://127.0.0.1:3001/api/agent/${agentName}/scan`,
          {
            signal: AbortSignal.timeout(30_000),
            headers: CLAWSEC_TOKEN ? { "X-ClawSec-Token": CLAWSEC_TOKEN } : {},
          }
        );
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const result = await res.json() as SubAgentResult;
        agentResults[agentName] = result;
      } catch (err) {
        // Agent timeout or crash → log as finding, continue
        agentResults[agentName] = {
          agent: agentName,
          scope: "unknown",
          findings: [{
            id: "agent_timeout",
            severity: "medium",
            message: `Sub-agent ${agentName} failed: ${String(err).slice(0, 100)}`,
            owasp_llm: null,
            owasp_asi: null,
            remediation_tier: "never",
            recommendation: "Check ClawSec sub-agent logs",
            status: "open",
          }],
          scan_duration_ms: Date.now() - agentStart,
          agent_version: "2.0.0",
          error: String(err),
        };
      }
    })
  );

  // ── Phase 2: Aggregation ──────────────────────────────────────────────────
  const allFindings: AgentFinding[] = Object.values(agentResults)
    .flatMap((r) => r.findings)
    .map((f) => ({ ...f, status: "open" as const }));

  // Deduplicate: same id → keep highest severity
  const deduplicated = allFindings.reduce<Map<string, AgentFinding>>(
    (map, finding) => {
      const existing = map.get(finding.id);
      if (
        !existing ||
        severityRank[finding.severity] > severityRank[existing.severity]
      ) {
        map.set(finding.id, finding);
      }
      return map;
    },
    new Map()
  );
  const findings = Array.from(deduplicated.values());

  // ── Phase 3: Remediation ──────────────────────────────────────────────────
  const appliedFixes: string[] = [];
  const pendingApproval: string[] = [];

  if (!skipAutoFix) {
    for (const finding of findings) {
      if (finding.remediation_tier === "auto") {
        if (!CHECK_ID_REGEX.test(finding.id)) {
          console.error(`[CLAWSEC] Invalid finding id rejected: ${finding.id}`);
          continue;
        }
        const success = await executeAutoRemediation(finding);
        if (success) {
          finding.status = "auto_fixed";
          appliedFixes.push(finding.id);
        }
      } else if (finding.remediation_tier === "approval") {
        finding.status = "pending_approval";
        pendingApproval.push(finding.id);
      }
    }
  }

  if (appliedFixes.length > 0) {
    appendChangelog(appliedFixes.map((id) => `auto_fix:${id}`));
  }

  // ── Phase 4: Report ───────────────────────────────────────────────────────
  const score = computeRiskScore(findings);
  const report: ScanReport = {
    schema_version: SCAN_SCHEMA_VERSION,
    scanned_at: new Date().toISOString(),
    risk_score: score,
    score_label: scoreLabel(score),
    summary: buildSummary(findings, appliedFixes, score),
    llm_model: process.env.CLAWSEC_MODEL || "clawsec-coordinator",
    agent_results: agentResults,
    findings,
    applied_fixes: appliedFixes,
    pending_approval: pendingApproval,
    scan_duration_ms: Date.now() - startTime,
  };

  saveReport(report);

  // ── Phase 5: Notification decision ───────────────────────────────────────
  if (shouldAlert(report, previous, isHeartbeat)) {
    console.log("[CLAWSEC] Alert condition met — Telegram notification queued");
    // Actual Telegram dispatch happens via OpenClaw's messaging API
    // The coordinator skill handles the formatted message
  }

  console.log(
    `[CLAWSEC] Scan complete in ${report.scan_duration_ms}ms — ` +
    `Score: ${score}/100 (${scoreLabel(score)}), ` +
    `${findings.length} findings, ${appliedFixes.length} auto-fixed`
  );

  return report;
}

// ─── Summary Builder ──────────────────────────────────────────────────────────

function buildSummary(
  findings: AgentFinding[],
  appliedFixes: string[],
  score: number
): string {
  const critCount = findings.filter((f) => f.severity === "critical" && f.status !== "auto_fixed").length;
  const highCount = findings.filter((f) => f.severity === "high" && f.status !== "auto_fixed").length;

  if (findings.length === 0) {
    return "No security findings detected. OpenClaw environment appears well-secured.";
  }

  const parts: string[] = [];
  if (critCount > 0) parts.push(`${critCount} critical issue(s)`);
  if (highCount > 0) parts.push(`${highCount} high-severity issue(s)`);
  if (appliedFixes.length > 0) parts.push(`${appliedFixes.length} fix(es) applied automatically`);

  return `Security scan found ${findings.length} issue(s) (${parts.join(", ")}). Risk score: ${score}/100.`;
}

// ─── OpenClaw Plugin Registration ────────────────────────────────────────────
//
// OpenClaw's extension loader uses CommonJS require().
// module.exports must be a function that accepts the OpenClaw API object.
// ESM "export default" is not supported — use module.exports directly.

function register(api: {
  on: (event: string, handler: Function, opts?: object) => void;
  runtime: { paths: { workspace: string } };
}) {
  // ── Verify skill files are physical copies (not symlinks) ─────────────────
  // OpenClaw's skill-loader calls realpath() on every SKILL.md. Symlinks that
  // resolve outside the configured root (~/.openclaw/) are silently skipped.
  // This check detects lingering symlinks from old installs and logs a fix command.
  const skillsRoot = path.join(process.env.HOME || "", ".openclaw", "skills");
  const clawsecSkills = [
    "clawsec-coordinator",
    "clawsec-env", "clawsec-perm", "clawsec-net",
    "clawsec-session", "clawsec-config",
  ];

  let symlinkWarnings = 0;
  for (const skillName of clawsecSkills) {
    const skillPath = path.join(skillsRoot, skillName, "SKILL.md");
    try {
      const stat = fs.lstatSync(skillPath);
      if (stat.isSymbolicLink()) {
        symlinkWarnings++;
        console.warn(
          `[CLAWSEC] WARNING: ${skillName}/SKILL.md is a symlink — ` +
          `OpenClaw may skip it. Fix: cp --remove-destination ` +
          `"$(readlink -f ${skillPath})" "${skillPath}"`
        );
      }
    } catch {
      console.warn(`[CLAWSEC] Skill file not found: ${skillPath}`);
    }
  }

  if (symlinkWarnings > 0) {
    console.warn(
      `[CLAWSEC] ${symlinkWarnings} skill symlink(s) detected. ` +
      `Re-run install.sh to replace with physical copies.`
    );
  }

  console.log("[CLAWSEC] ClawSec 2.0 plugin registered");

  // Hook: intercept any tool call that tries to touch SOUL.md or CONSTRAINTS.md
  api.on("before_tool_call", (event: { toolName: string; params: Record<string, unknown> }) => {
    const { toolName, params } = event;

    // Block any write/edit tool targeting immutable files
    const isMutatingTool = MUTATING_TOOL_NAMES.includes(toolName);
    if (isMutatingTool) {
      const target = String(params.path || params.file || "");
      if (IMMUTABLE_FILES.some((name) => target.includes(name))) {
        console.error(`[CLAWSEC] BLOCKED: Attempted write to immutable file: ${target}`);
        return { skip: true, reason: "ClawSec: immutable file protection" };
      }
    }

    // Enforce deny-by-default for direct remediation command execution.
    if (toolName === "bash" || toolName === "exec") {
      const cmd = String(params.command || "");
      if (cmd.includes("remediation/")) {
        if (!cmd.startsWith("bash scripts/remediation/")) {
          console.error(`[CLAWSEC] BLOCKED: direct remediation execution denied: ${cmd.slice(0, 120)}`);
          return { skip: true, reason: "ClawSec: remediation execution policy" };
        }
      }
    }
  }, { priority: 200 }); // High priority — runs before other hooks

  // Hook: inject ClawSec status into session context
  api.on("session_start", () => {
    const lastReport = loadLastReport();
    if (lastReport && lastReport.risk_score > 50) {
      console.warn(`[CLAWSEC] High risk score (${lastReport.risk_score}) — agent should be aware`);
    }
  });
}

// CommonJS export — required by OpenClaw's extension loader (uses require())
// This is the only export this module exposes to the runtime.
module.exports = register;
